# version: '3'
# WARN[0000] ... the attribute `version` is obsolete, it will be ignored,
# please remove it to avoid potential confusion
services:
  pgrest:
    image: postgrest/postgrest
    ports:
      - "${PGRST_PORT:-3001}:3000"
    environment:
      PGRST_DB_URI: ${PGRST_DB_URI:-postgres://app_user:password@db:5432/app_db}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3001
      PGRST_DB_ANON_ROLE: ${PGRST_QUERY_ROLE:-web_anon}
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-api}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET:-GenerateASecretWithDevUrandomSeeReadme}
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    ports:
      - "${PG_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${PG_DB:-app_db}
      POSTGRES_USER: ${PG_USER:-app_user}
      POSTGRES_PASSWORD: ${PG_PW:-password}
  # Uncomment volumes if you want to persist the data.
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
