CREATE TABLE api.messages (
    id int primary key generated by default as identity,
    msg TEXT NOT NULL,
    username TEXT NOT NULL,
    room TEXT NOT NULL,
    created TIMESTAMP NOT NULL
);

create role chat_user nologin;
grant chat_user to authenticator;

grant usage on schema api to chat_user;
grant all on api.messages to chat_user;
